services:
  postgres:
    image: postgres:16
    container_name: risk-postgres
    restart: always
    environment:
      POSTGRES_DB: riskdb
      POSTGRES_USER: riskuser
      POSTGRES_PASSWORD: riskpass
    ports:
      - "5463:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: