spring.application.name=risk-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5463/riskdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:riskuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:riskpass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

management.info.env.enabled=true


info.app.name=Risk Assessment API
info.app.description=REST API for customer risk assessment and scoring
info.app.version=${APP_VERSION:dev}
info.app.author=Adriano Reckziegel

logging.level.org.springframework.security=${LOGGING_LEVEL_SPRING_SECURITY:INFO}

jwt.secret=${JWT_SECRET:VGhpc0lzQVNlY3JldEtleUZvck15Umlza0FwaVByb2plY3Q=}
jwt.expiration=${JWT_EXPIRATION:3600000}

app.bootstrap-admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap-admin.username=${APP_BOOTSTRAP_ADMIN_USERNAME:admin}
app.bootstrap-admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:admin123}

server.forward-headers-strategy=framework
