spring.application.name=risk-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5463/riskdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:riskuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:riskpass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

management.info.env.enabled=true


info.app.name=Risk Assessment API
info.app.description=REST API for customer risk assessment and scoring
info.app.version=${APP_VERSION:dev}
info.app.author=Adriano Reckziegel

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET:VGhpc0lzQVNlY3JldEtleUZvck15Umlza0FwaVByb2plY3Q=}
jwt.expiration=${JWT_EXPIRATION:3600000}
