on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: riskdb
          POSTGRES_USER: riskuser
          POSTGRES_PASSWORD: riskpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U riskuser -d riskdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5



    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/riskdb
          SPRING_DATASOURCE_USERNAME: riskuser
          SPRING_DATASOURCE_PASSWORD: riskpass
        run: ./mvnw test

      - name: Build application
        run: ./mvnw package -DskipTests

      - name: Build Docker image
        run: docker build -t risk-api:ci .